package duongcaotung.excercise_final.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;

import duongcaotung.excercise_final.student.model.DataBase;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Duong Cao Tung
 */
public class Add_Class extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form Add_Class
	 */
	public Add_Class() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lbTenLop = new javax.swing.JLabel();
		lbChuyenNganh = new javax.swing.JLabel();
		lbKhoa = new javax.swing.JLabel();
		tfTenLop = new javax.swing.JTextField();
		tfChuyenNganh = new javax.swing.JTextField();
		tfKhoa = new javax.swing.JTextField();
		jbtLuu = new javax.swing.JButton();
		jbtHuy = new javax.swing.JButton();
		jbtThoat = new javax.swing.JButton();

		setTitle("Thêm mới lớp học");
		setLocation(500, 200);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lbTenLop.setText("Tên Lớp");

		lbChuyenNganh.setText("Chuyên Ngành");

		lbKhoa.setText("Khoa");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addGap(105)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(lbChuyenNganh, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(lbTenLop, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lbKhoa))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false).addComponent(tfKhoa)
						.addComponent(tfChuyenNganh, GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
						.addComponent(tfTenLop))
				.addContainerGap(17, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(tfTenLop, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbTenLop))
						.addGap(47)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(tfChuyenNganh, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbChuyenNganh))
						.addGap(44)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(tfKhoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbKhoa))
						.addContainerGap(49, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		jbtLuu.setText("Lưu");
		jbtLuu.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				// ket noi sql

				Connection connection = DataBase.connected();
				String tenLop = tfTenLop.getText();
				String chuyenNganh = tfChuyenNganh.getText();
				String khoa = tfKhoa.getText();
				if (tenLop.isEmpty()) {
					JOptionPane.showMessageDialog(tfTenLop, this, "Vui lòng nhập tên lớp", getDefaultCloseOperation());
				}
				if (chuyenNganh.isEmpty()) {
					JOptionPane.showMessageDialog(tfChuyenNganh, this, "Vui lòng nhập chuyên ngành",
							getDefaultCloseOperation());
				}
				if (khoa.isEmpty()) {
					JOptionPane.showMessageDialog(tfKhoa, this, "Vui lòng nhập tên khoa", getDefaultCloseOperation());
				}
				PreparedStatement preparedStatement;
				String sqlInsert = "INSERT [dbo].[Class] ([Name], [Major], [Khoa]) VALUES (?, ?, ?)";
				try {
					preparedStatement = connection.prepareStatement(sqlInsert);
					preparedStatement.setString(1, tenLop);
					preparedStatement.setString(2, chuyenNganh);
					preparedStatement.setString(3, khoa);
					preparedStatement.executeUpdate();
					JOptionPane.showMessageDialog(jbtLuu, "Lớp " + tenLop + " đã được tạo", "Thêm Lớp", 0);
				} catch (Exception e2) {
					// TODO: handle exception
				}
			}

		});

		jbtHuy.setText("Hủy");
		jbtHuy.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				tfTenLop.setText("");
				tfChuyenNganh.setText("");
				tfKhoa.setText("");
			}
		});

		jbtThoat.setText("Thoát");
		jbtThoat.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				dispose();
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(250, 250, 250).addComponent(jbtLuu).addGap(40, 40, 40)
						.addComponent(jbtHuy).addGap(40, 40, 40).addComponent(jbtThoat)
						.addContainerGap(241, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jbtLuu).addComponent(jbtHuy).addComponent(jbtThoat))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Add_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Add_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Add_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Add_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Add_Class().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jbtLuu;
	private javax.swing.JButton jbtHuy;
	private javax.swing.JButton jbtThoat;
	private javax.swing.JLabel lbTenLop;
	private javax.swing.JLabel lbChuyenNganh;
	private javax.swing.JLabel lbKhoa;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField tfTenLop;
	private javax.swing.JTextField tfChuyenNganh;
	private javax.swing.JTextField tfKhoa;
	SQLServerDataSource dataSource = new SQLServerDataSource();
	// End of variables declaration
}
