/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duongcaotung.excercise_final.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

import duongcaotung.excercise_final.student.model.DataBase;

/**
 *
 * @author Duong Cao Tung
 */
public class Add_Student extends javax.swing.JFrame {
	static Vector vector;

	/**
	 * Creates new form Add_Student
	 */
	public Add_Student() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lbName = new javax.swing.JLabel();
		lbAddress = new javax.swing.JLabel();
		lbIdNumber = new javax.swing.JLabel();
		lbPhoneNumber = new javax.swing.JLabel();
		lbGender = new javax.swing.JLabel();
		lbClassName = new javax.swing.JLabel();
		tfName = new javax.swing.JTextField();
		tfAddress = new javax.swing.JTextField();
		tfIdNumber = new javax.swing.JTextField();
		tfPhoneNumber = new javax.swing.JTextField();
		jbtSave = new javax.swing.JButton();
		jbtCancel = new javax.swing.JButton();
		jbtClose = new javax.swing.JButton();
		rdbFemale = new javax.swing.JRadioButton();
		rdbMale = new javax.swing.JRadioButton();
		cbClass = new javax.swing.JComboBox<>();

		setTitle("Thêm mới sinh viên");
		setLocation(500, 200);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lbName.setText("Họ Tên");

		lbAddress.setText("Địa chỉ");

		lbIdNumber.setText("Số chứng minh");

		lbPhoneNumber.setText("Số điện thoại");

		lbGender.setText("Giới tính");

		lbClassName.setText("Lớp học");

		jbtSave.setText("Lưu");
		jbtSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
				String stdName = tfName.getText();
				String stdAddress = tfAddress.getText();
				String stdIdNumber = tfIdNumber.getText();
				String stdPhoneNumber = tfPhoneNumber.getText();

				// gender
				String stdgender = "";
				if (rdbFemale.isSelected()) {
					stdgender = "Nữ¯";
				} else {
					stdgender = "Nam";
				}
				// Class
				String stdClass = cbClass.getSelectedItem().toString();
				//

				if (stdName.isEmpty()) {
					JOptionPane.showMessageDialog(tfName, this, "Vui Lòng Nhập Tên", getDefaultCloseOperation());
					tfName.requestFocus();
					return;
				}
				if (stdAddress.isEmpty()) {
					JOptionPane.showMessageDialog(tfAddress, this, "Vui Lòng Nhập Địa Chỉ", getDefaultCloseOperation());
					tfAddress.requestFocus();
					return;
				}
				if (stdIdNumber.isEmpty()) {
					JOptionPane.showMessageDialog(tfIdNumber, this, "Vui Lòng Nhập Số CMND",
							getDefaultCloseOperation());
					tfIdNumber.requestFocus();
					return;
				}
				String sqlInsert = "INSERT [dbo].[Student] ([Name], [Address], [ClassName], [IdNumber], [PhoneNumber], [Gender]) "
						+ "VALUES (?,?,?,?,?,?)";
				//
				try {
					Connection connection = DataBase.connected();
					PreparedStatement preparedStatement = null;
					preparedStatement = connection.prepareStatement(sqlInsert);
					preparedStatement.setString(1, stdName);
					preparedStatement.setString(2, stdAddress);
					preparedStatement.setString(3, stdClass);
					preparedStatement.setString(4, stdIdNumber);
					preparedStatement.setString(5, stdPhoneNumber);
					preparedStatement.setString(6, stdgender);
					vector = new Vector<>();
					vector.add(stdName);
					vector.add(stdAddress);
					vector.add(stdClass);
					vector.add(stdIdNumber);
					vector.add(stdPhoneNumber);
					vector.add(stdgender);
					List_Student.defaultTableModel.addRow(vector);
					;

					preparedStatement.executeUpdate();
					JOptionPane.showMessageDialog(jbtSave, "Đã tạo mới sinh viên", "Thêm mới", 0);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jbtCancel.setText("Hủy");
		jbtCancel.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				tfName.setText("");
				tfIdNumber.setText("");
				tfPhoneNumber.setText("");
				tfAddress.setText("");
				cbClass.setSelectedItem(null);
			}
		});

		jbtClose.setText("Đóng");
		jbtClose.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				dispose();
				;
			}
		});

		rdbFemale.setText("Nữ");
		rdbMale.setText("Nam");
		ButtonGroup btg = new ButtonGroup();
		btg.add(rdbFemale);
		btg.add(rdbMale);

		// Xử lý combo box
		List<String> list = new ArrayList<>();
		try {
			String sql = "select Name from Class";
			Connection connection = DataBase.connected();
			Statement statement = connection.createStatement();
			ResultSet resultSet = statement.executeQuery(sql);
			while (resultSet.next()) {
				list.add(resultSet.getString("Name"));
			}
			for (String item : list) {
				cbClass.addItem(item);
			}
		} catch (Exception e) {
			// TODO: handle exception
		}

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(90, 90, 90).addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbIdNumber, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbGender, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbClassName, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(68, 68, 68)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 380,
																Short.MAX_VALUE)
														.addComponent(tfAddress))
												.addComponent(tfIdNumber, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 380,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(tfPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 380,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(cbClass, javax.swing.GroupLayout.Alignment.LEADING, 0,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(rdbFemale)
														.addGap(18, 18, 18).addComponent(rdbMale)))))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(177, 177, 177).addComponent(jbtSave)
								.addGap(50, 50, 50).addComponent(jbtCancel).addGap(50, 50, 50).addComponent(jbtClose)))
						.addContainerGap(93, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbName).addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(34, 34, 34)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbAddress).addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(34, 34, 34)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbIdNumber)
								.addComponent(tfIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(34, 34, 34)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbPhoneNumber)
								.addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbGender).addComponent(rdbFemale).addComponent(rdbMale))
						.addGap(32, 32, 32)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbClassName).addComponent(cbClass, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jbtSave).addComponent(jbtCancel).addComponent(jbtClose))
						.addGap(55, 55, 55)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(84, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Add_Student().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jbtSave;
	private javax.swing.JButton jbtCancel;
	private javax.swing.JButton jbtClose;
	private javax.swing.JComboBox<String> cbClass;
	private javax.swing.JLabel lbName;
	private javax.swing.JLabel lbAddress;
	private javax.swing.JLabel lbIdNumber;
	private javax.swing.JLabel lbPhoneNumber;
	private javax.swing.JLabel lbGender;
	private javax.swing.JLabel lbClassName;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton rdbFemale;
	private javax.swing.JRadioButton rdbMale;
	private javax.swing.JTextField tfName;
	private javax.swing.JTextField tfAddress;
	private javax.swing.JTextField tfIdNumber;
	private javax.swing.JTextField tfPhoneNumber;

	// End of variables declaration
}
