/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duongcaotung.excercise_final.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;

import duongcaotung.excercise_final.student.model.DataBase;
import duongcaotung.excercise_final.student.model.Student;

/**
 *
 * @author Duong Cao Tung
 */
public class List_Student extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form List_Student
	 */
	public List_Student() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jbtAddStd = new javax.swing.JButton();
		jbtAddCls = new javax.swing.JButton();
		jbtEdit = new javax.swing.JButton();
		jbtDelete = new javax.swing.JButton();
		jbtClose = new javax.swing.JButton();

		setTitle("Danh sách sinh viên");
		setLocation(500, 200);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		Connection connection = DataBase.connected();

		jScrollPane1.setViewportView(table);
		if (table.getColumnModel().getColumnCount() > 0) {
			table.getColumnModel().getColumn(0).setPreferredWidth(50);
			table.getColumnModel().getColumn(1).setPreferredWidth(100);
			table.getColumnModel().getColumn(2).setPreferredWidth(100);
			table.getColumnModel().getColumn(3).setPreferredWidth(50);
			table.getColumnModel().getColumn(4).setPreferredWidth(100);
			table.getColumnModel().getColumn(5).setPreferredWidth(50);
		}
		//

		updateData(connection);
		//

		jbtAddStd.setText("Thêm SV");
		//
		jbtAddStd.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				Add_Student add_Student = new Add_Student();
				add_Student.show();
				Vector student = add_Student.vector;
				defaultTableModel.addRow(student);

			}
		});
		//
		jPanel1.add(jbtAddStd);
		//
		jbtAddCls.setText("Thêm Lớp");
		jbtAddCls.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				Add_Class add_Class = new Add_Class();
				add_Class.show();
			}
		});
		jPanel1.add(jbtAddCls);

		jbtEdit.setText("Sửa");
		jbtEdit.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				int selectedRow = table.getSelectedRow();
				String stdName = defaultTableModel.getValueAt(selectedRow, 0).toString();
				String stdAddress = defaultTableModel.getValueAt(selectedRow, 1).toString();
				String stdClass = defaultTableModel.getValueAt(selectedRow, 2).toString();
				String stdIdNumber = defaultTableModel.getValueAt(selectedRow, 3).toString();
				String stdPhoneNumber = defaultTableModel.getValueAt(selectedRow, 4).toString();
				String sql = "Update Student set Name=?, Address=?, ClassName=?,"
						+ " IdNumber=?, PhoneNumber=? where IdNumber= " + stdIdNumber;
				try {
					PreparedStatement preparedStatement = connection.prepareStatement(sql);
					preparedStatement.setString(1, stdName);
					preparedStatement.setString(2, stdAddress);
					preparedStatement.setString(3, stdClass);
					preparedStatement.setString(4, stdIdNumber);
					preparedStatement.setString(5, stdPhoneNumber);
					preparedStatement.executeUpdate();
					JOptionPane.showMessageDialog(jbtEdit, "Đã Thay Đổi Thông Tin", "Updated", 0);
				} catch (Exception e2) {
					// TODO: handle exception
				}
			}
		});
		jPanel1.add(jbtEdit);

		jbtDelete.setText("Xóa");
		// -----------------------------------------------------------------------------
		jbtDelete.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				DataBase.connected();
				// defaultTableModel = (DefaultTableModel) table.getModel();
				int selectedRow = table.getSelectedRow();
				String stdIdNumber = defaultTableModel.getValueAt(selectedRow, 3).toString();
				System.out.println("Đã xóa SV: " + stdIdNumber);
				String sql = "delete from Student where IdNumber = ?";
				try {
					PreparedStatement statement = connection.prepareStatement(sql);
					statement.setString(1, stdIdNumber);
					statement.executeUpdate();
					JOptionPane.showMessageDialog(jbtDelete, "Đã xóa sinh viên " + stdIdNumber, "Delete", 0);

				} catch (Exception e2) {
					// TODO: handle exception
				}
				defaultTableModel.removeRow(selectedRow);
			}
		});
		// -----------------------------------------------------------------------------

		jPanel1.add(jbtDelete);

		jbtClose.setText("Đóng");
		jbtClose.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				System.exit(0);
			}
		});
		jPanel1.add(jbtClose);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 11, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	void updateData(Connection connection) {
		ResultSet resultSet;
		String sql = "select * from Student";
		try {
			Statement statement = connection.createStatement();
			resultSet = statement.executeQuery(sql);
			Vector data;

			while (resultSet.next()) {
				data = new Vector();
				data.add(resultSet.getString(1));
				data.add(resultSet.getString(2));
				data.add(resultSet.getString(3));
				data.add(resultSet.getString(4));
				data.add(resultSet.getString(5));
				defaultTableModel.addRow(data);
				table.setRowHeight(50);
				table.setModel(defaultTableModel);
			}
			resultSet.close();

		} catch (Exception e) {
			// TODO: handle exception
			Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, e);

		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(List_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(List_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(List_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(List_Student.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new List_Student().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jbtAddStd;
	private javax.swing.JButton jbtAddCls;
	private javax.swing.JButton jbtEdit;
	private javax.swing.JButton jbtDelete;
	private javax.swing.JButton jbtClose;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable table;
	SQLServerDataSource dataSource = new SQLServerDataSource();
	static String header[] = { "Name", "Address", "ClassName", "IdNumber", "PhoneNumber" };
	static DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);

	// End of variables declaration
}
